task_name: "single_component_mp_scaffold"
split_type: "frozen_scaffold_cv"
use_frozen_split: true
split_dir: "splits/scaffold"
split_manifest: "splits/scaffold/split_manifest.csv"
data_dir: "data"
outputs_root: "outputs"
model_name_or_path: "PATH_OR_HF_ID_TO_MOLFORMER"
seed: 516
n_folds: 5
batch_size: 256
num_workers: 8
max_epochs: 300
freeze_bert_epochs: 3
final_tune_epochs: 5
bert_encoder_lr: 1e-6
bert_projection_lr: 1e-5
dmpnn_lr: 3e-4
fusion_lr: 8.19e-5
bert_encoder_weight_decay: 1e-2
bert_projection_weight_decay: 1e-2
dmpnn_weight_decay: 1e-5
fusion_weight_decay: 2.49e-2
dropout: 0.325
xtb_hidden_dim: 128
common_hidden_dim: 192
xtb_depth: 3
dmpnn_hidden_dim: 128
dmpnn_output_dim: 128
dmpnn_layers: 4
dmpnn_dropout: 0.2
use_rdkit_in_xtb: true
readout_dim: 16
dynamic_weight_scale: 1.0
bias_hidden_dim: 64
main_branch_noise_std: 0.002
grad_accum_steps: 1
max_length: 200
huber_delta: 0.5
final_lr_scale: 0.3
clip_grad_norm: 1.0
cache_graphs: true
multi_gpu_mode: "none"
gpu_ids: ""
device: ""
